create sequence hibernate_sequence start with 1 increment by 1;
create table books (id bigint not null, author varchar(255), copies integer, description varchar(250) not null, isbn varchar(50) not null, name varchar(100) not null, serial_name varchar(50) not null, primary key (id));
create table books_users (book_id bigint not null, user_id bigint not null, primary key (book_id, user_id));
create table user (id bigint generated by default as identity, name varchar(100) not null, primary key (id));
alter table books add constraint UK_kibbepcitr0a3cpk3rfr7nihn unique (isbn);
alter table user add constraint UK_gj2fy3dcix7ph7k8684gka40c unique (name);
alter table books_users add constraint FK4g1ewcd4tvi8ahc2anedtp77q foreign key (user_id) references user;
alter table books_users add constraint FKkn0b6th3avh42vj187mjb5hga foreign key (book_id) references books;


insert into user (id, name) values (1, 'Rohan');
insert into user (id, name) values (2, 'Roy');
insert into books (id, author, copies, description, isbn, name, serial_name) values (1, 'RK', 4, 'Description', 'F-ISBN', 'Finance', 'S-NUM-F');
insert into books (id, author, copies, description, isbn, name, serial_name) values (2, 'MK', 6, 'Description', 'S-ISBN', 'Spirit', 'S-NUM-S');
insert into books (id, author, copies, description, isbn, name, serial_name) values (3, 'PK', 8, 'Description', 'C-ISBN', 'Comic', 'S-NUM-C');
